//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditCell
{
    
    
    /// <summary>
    ///  A strongly-typed ImageManager class, for looking up global images.
    /// </summary>
    // This class was auto-generated by the ImageManagerBuilder
    // class via a Resco ImageManager tool.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageManager1
    {
        
        private static global::Resco.ImageManager.ImageManager _imageManager;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageManager1()
        {
        }
        
        /// <summary>
        ///  Returns the cached ImageManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::Resco.ImageManager.ImageManager ImageManager
        {
            get
            {
                if (object.ReferenceEquals(_imageManager, null))
                {
                    _imageManager = new global::Resco.ImageManager.ImageManager(typeof(ImageManager1));
                }
                return _imageManager;
            }
        }
        
        /// <summary>
        ///  Returns the cached Image used by this class.
        /// </summary>
        internal static global::System.Drawing.Bitmap GetImage(string name)
        {
            return ImageManager.GetImage(name);
        }
    }
}
